### ISSUE TITLE
can't see any of saved convos

### ISSUE THREAD

**Issue by alexdobrenko** [a16z-infra/ai-town#117]
i can't tell if my ppl are talking to each other. I have the AI-town running on the local machine but can't read any past convos. 
![image](https://github.com/a16z-infra/ai-town/assets/5139334/a607005c-dd73-4c70-b6ee-796ef2bcda6f)
 
![image](https://github.com/a16z-infra/ai-town/assets/5139334/13a355f5-30a6-46e6-9827-b4e9c3730474)

I tried using npx convex run init:reset but then I get this 

![image](https://github.com/a16z-infra/ai-town/assets/5139334/b602c35f-407b-4c72-82d3-e424d29608de)

I am sure I'm doing something very silly wrong -- any idea what that might be?

**Comment by 61cygni** [comment]
Have you checked the Convex dashboard?

Run "npx convex dashboard" from the project root. All the game state is in
the dashboard.

.m

**Comment by alexdobrenko** [comment]
yes but I can't find any info on the conversations themselves it feels like they're just not happening 
![image](https://github.com/a16z-infra/ai-town/assets/5139334/81000ca5-530f-4592-898c-e9b29add8931)

**Comment by mrrenneNoble** [comment]
Any resolution. Getting the exact same thing. Running locally.

**Comment by ianmacartney** [comment]
The messages from that version were stored in the `journal` table - there are some queries in `testing.ts` if you want to fetch messages for a specific conversation - with something like `npx convex run testing:someFunction`
