### ISSUE TITLE
is ai town launguge model must be using openai's GPT api?

### ISSUE THREAD

**Issue by jimmy8399** [a16z-infra/ai-town#133]
is ai town launguge model must be using openai's GPT api?  or its option ?

**Comment by martinezpl** [comment]
There's no other option at the moment. Feel free to add another integration.

**Comment by chatsci** [comment]
What if I want to test a local language model, such as LLaMA? how should I revise the code?

**Comment by 61cygni** [comment]
We're working on that. It's not supported yet.

**Comment by ianmacartney** [comment]
What are all the models folks would like to see? 
- LLaMA on Replicate
- LLaMA locally

Those are the top requests I've seen - any other interesting ones? And are folks looking for the `llama-2-70b-chat` or something else?

**Comment by babytdream** [comment]
want to use `llama-2-70b-chat ` locally

**Comment by ianmacartney** [comment]
In #184 we add Ollama support which you can run locally for chat (but not any embeddings yet)

**Comment by ianmacartney** [comment]
It landed! try it out and let us know how it's working for you. documented in readme
