### ISSUE TITLE
Can I change the language to model to replicate/llama-2-70b-chat?

### ISSUE THREAD

**Issue by izzuddin-noormy** [a16z-infra/ai-town#138]

**Comment by yanmengxiang1** [comment]
@ianmacartney 
Hello, I  use openai's proxy server to implement llama2, I only modified the following code:
![image](https://github.com/a16z-infra/ai-town/assets/117291738/86d8e505-914f-4200-ad2d-4a8e228a3f94)
![image](https://github.com/a16z-infra/ai-town/assets/117291738/8504093d-f364-4136-bf37-b6e32714bb59)

But the agent have no normal conversation：
![image](https://github.com/a16z-infra/ai-town/assets/117291738/37e0be77-8891-4b2b-a962-50d0c628f8c3)

you can test  this openai's proxy in this `*.html` in google：
[html.txt](https://github.com/a16z-infra/ai-town/files/13059810/html.txt)
Do you have time to test this interface? Thank you.

**Comment by ianmacartney** [comment]
Landed - reopen if it doesn't suite your needs. Hopefully pointing the URL to replicate works, I've only tested with local llama
