### ISSUE TITLE
Feature about deployment

### ISSUE THREAD

**Issue by Formyselfonly** [a16z-infra/ai-town#178]
Bro,Can I ask u some question?If u can answer or not,I will be very thankful!
The quetsion:
1.Why I can't use the interact button with my own deployment?Is the demo code same with the source code u provide?
2.How to reduce the consume of the apikey? Can I make them talk less to reduce the token consume?

**Comment by 61cygni** [comment]
- The latest branch (as of last night) should fix the interact bug
- One of the best ways to reduce api calls is to reduce the number of AIs.
One way to do that is to pass as an arg on the command line. For example,
update your package.json to the following:

    "dev:init": "npx convex run init '{\"numAgents\" : 2}'",

**Comment by Formyselfonly** [comment]
I am very pleasure to get your answer. Thanks bro

**Comment by ianmacartney** [comment]
You will want to run `npx convex run testing:wipeAllTables` before restarting `npm run dev` after making the change
