### ISSUE TITLE
How to use another LLMs model?

### ISSUE THREAD

**Issue by Formyselfonly** [a16z-infra/ai-town#187]
Hello, awesome developer
I don't want to use ChatGPT, I want to use some free LLMs model, or I build a local LLMs and use this.

**Comment by Formyselfonly** [comment]
upvote!

**Comment by ianmacartney** [comment]
OLlama is now working and documented in the readme! 🎉

**Comment by Formyselfonly** [comment]
> OLlama is now working and documented in the readme! 🎉

Bro,Thanks for your answer!
