### ISSUE TITLE
Where are the textures?

### ISSUE THREAD

**Issue by nukeop** [a16z-infra/ai-town#202]
Hi, there are references to spritesheets such as `32x32folk.png`, but I can't find them in the repo. I'd like to know what they look like so that I can replace them with my own. Could you please tell me where I can find them?

**Comment by filmsaremyalc** [comment]
If you're in VSCode, just click `cmd + p`, type in `32x32folk.png`, and it should come up in `public/assets`.

**Comment by nukeop** [comment]
Great, thank you!
