### ISSUE TITLE
no convex/config.ts? and no just?

### ISSUE THREAD

**Issue by menguzat** [a16z-infra/ai-town#237]
I downloaded and installed the convex binary as explained.

However, in my ai-town folder, there is no file ./convex/config.ts

and when I try npm run dev I get:

> ai-town@0.0.0 predev
> just convex dev --run init --until-success

'just' is not recognized as an internal or external command,
operable program or batch file.

what am I doing wrong?
I'm on windows 11.

**Comment by 61cygni** [comment]
It's convex/constants.ts we need to update the README for that.

You'll need to install just. I don't know how to do that on Windows ...

You're probably best using Pinokio (https://pinokio.computer/) if
installing AI town on Windows.
.m

**Comment by ianmacartney** [comment]
There's a link in the README on installing just: https://github.com/casey/just?tab=readme-ov-file#installation
