### ISSUE TITLE
Convex Local Backend error and termination

### ISSUE THREAD

**Issue by MCPE10** [a16z-infra/ai-town#240]
After running the convex local backend, it starts up and runs for a bit then says:

2024-06-05T03:07:16.570412Z  INFO application::scheduled_jobs: Executing aiTown/main.js:runStep!
convex-local-backend(14063,0x16eb5f000) malloc: *** error for object 0x600001b5d7f0: pointer being freed was not allocated
convex-local-backend(14063,0x16eb5f000) malloc: *** set a breakpoint in malloc_error_break to debug

I have been troubleshooting this for a long time and still haven't found a way to make it work. Can anyone tell me what these errors mean and what steps I should take to solve them?

**Comment by ianmacartney** [comment]
Is this on the latest version of the local backend binary? Can you share what version? I hit an issue like this and the team found a bug in the new version of rust (😱) and rolled back temporarily, but that was weeks ago
