### ISSUE TITLE
Getting Pointer being free is not allocated error in convex-local-backend

### ISSUE THREAD

**Issue by PeterTongHu** [a16z-infra/ai-town#241]
Hi all, right now I am experiencing this error while running convex-local-backend.
<img width="902" alt="Screenshot 2024-06-05 at 11 11 15 AM" src="https://github.com/a16z-infra/ai-town/assets/65619454/07c39f11-2810-46d4-8eae-d43b6da5e909">
Any idea what happened?

**Comment by MCPE10** [comment]
Same error within 1 minute! Go to issues #240 , same error there.

**Comment by ianmacartney** [comment]
Yeah let's just track it in #240
