### ISSUE TITLE
Has anyone encountered Unexpected end of JSON input error

### ISSUE THREAD

**Issue by PeterTongHu** [a16z-infra/ai-town#242]
Here is the error:
Generating messages keep timing out, and there has been Unexpected end of JSON input error.
<img width="1116" alt="Screenshot 2024-06-05 at 5 57 52 PM" src="https://github.com/a16z-infra/ai-town/assets/65619454/afe30496-5879-4869-8668-4166133934d0">

**Comment by ianmacartney** [comment]
I wonder if the llm is giving up and not sending back a full response - you could try catching the error in `llm.ts` and printing what the response was - maybe `await response.text()` would return something? My guess is this is running against local ollama?

**Comment by bruno686** [comment]
> 这是错误： 生成消息一直超时，并且出现 JSON 输入意外结束错误。 <img alt="截图于 2024-06-05 下午 5 点 57 分 52 秒" width="1116" src="https://private-user-images.githubusercontent.com/65619454/336787659-afe30496-5879-4869-8668-4166133934d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDQ4MjgsIm5iZiI6MTczNTIwNDUyOCwicGF0aCI6Ii82NTYxOTQ1NC8zMzY3ODc2NTktYWZlMzA0OTYtNTg3OS00ODY5LTg2NjgtNDE2NjEzMzkzNGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYjcxOTc5YzBjYjQwMzY1MTRkYTJiOTNkZjIxYWU1MmRhMzEyYTEzZDFlOWJkNmE2MTUwZDkwNzRlNTQ5NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8GyQjRvWZ4kufTgR50wkX95eCR3Mact0Aiptamhy1xo">

Have you run this project successfully?
