### ISSUE TITLE
language setting

### ISSUE THREAD

**Issue by ruanjianlun** [a16z-infra/ai-town#246]
How to change the language of the game? when i use Pinokio

**Comment by ianmacartney** [comment]
I think you can change all the prompts to another language and hopefully
the LLM follow along. The character bios in data/characters.ts, the prompts
in convex/agent/conversation.ts and convex/agent/memory.ts

**Comment by ruanjianlun** [comment]
Thanks for your help, I will try the following. .

**Comment by Ikkitsuna** [comment]
To make sure of the change of language and make the model understand well to inform in your language, first make sure that your model manages your language then in \data\characters.ts, modify the personality of the ai to integrate them that they must imperatively understand and speak ONLY your language example so below with French.

 ```
{
   name: 'Lucky',
   character: 'f1',
   identity: `Lucky est toujours heureux et curieux, et il adore le fromage. Il passe
    la plupart de son temps à lire sur l'histoire de la science et à voyager
    à travers la galaxie sur n'importe quel vaisseau qui l'emmènera. Il est très articulé et
    infiniment patient, sauf quand il voit un écureuil. Il est également incroyablement loyal et courageux.
    Lucky vient de revenir d'une incroyable aventure spatiale pour explorer une planète lointaine
    et il est très excité de raconter cela aux gens. Il est également très bon pour raconter des histoires et parle et comprend UNIQUEMENT le français.`,
   plan: 'Tu veux entendre tous les potins.',
  },
```

**Comment by ruanjianlun** [comment]
Thank you for your reply, it is very helpful. I hope you are happy every day


Ikkitsuna ***@***.***> 于2024年7月6日周六 13:51写道：
