### ISSUE TITLE
is there a way to show convex dashboard on local by visiting http://127.0.0.1:3210/?

### ISSUE THREAD

**Issue by quanchentg** [a16z-infra/ai-town#257]
This is an awesome project.
I successfully make it running on my local. 
I am curious about is there way to have a dashboard in local using convex?
Please correct me directly if I have some misunderstanding here?

Thanks for your time and patience.

**Comment by ianmacartney** [comment]
That is correct - currently you're limited to using the CLI or exploring
the SQLite file with another tool locally. There will be updates on running
things locally with a dashboard in Discord: convex.dev/community
We have a version of it working internally but we're still testing and
iterating on it.
