### ISSUE TITLE
Debug `playerRelations` object in agent.ts

### ISSUE THREAD

**Issue by ykhli** [a16z-infra/ai-town#56]
Today `playerRelations` object in agent.ts contains the wrong data: if the currently speaking player's name is `Lucky`, `playerRelations` is referencing `Lucky` again, making the speaking player thinks they are talking to themselves. 

We should fix this so playerRelations contains relationship data between the speaking player and a list of audience they are speaking to.

**Comment by pieteradejong** [comment]
I'm fluent in TypeScript and would like to contribute to this project. 
Happy to spend some time to familiarize with code base and determine whether I see a path to fixing this issue.

**Comment by ianmacartney** [comment]
I believe https://github.com/a16z-infra/ai-town/commit/27e8451e919b38ec5d626b36610fe1e0c7d2c1b5 fixed this . if it shows up again please re-open!
