### ISSUE TITLE
Use offline with OpenAI compatible open source API and Pinecone alternative?

### ISSUE THREAD

**Issue by sammcj** [a16z-infra/ai-town#86]
Cool project!

It would be neat if this could be run locally / offline without the need for cloud services or subscriptions.

Tools such as [LocalAI](https://localai.io), [Text Generation Web UI](https://github.com/oobabooga/text-generation-webui), [LM Studio](https://lmstudio.ai/) provide OpenAI compatible API and functionality - from my experience it's as simple setting the API endpoint.

However with Pinecone - I'm not sure how standard it is, I've seen other projects using [Chroma](https://www.trychroma.com/) and [Weaviate](https://github.com/weaviate/weaviate) but I'm not sure if they're pluggable.

**Comment by ianmacartney** [comment]
You could set the openAI base URL to a url proxied to your local machine using ngrok, if it's actually a drop-in replacement. Have you tried that? The env variable to set in Convex is `OPENAI_API_BASE`

**Comment by ianmacartney** [comment]
This is now the default

**Comment by sammcj** [comment]
Awesome work Ian!
