### ISSUE TITLE
Unhandled runtime error clerk browser

### ISSUE THREAD

**Issue by ericvh** [a16z-infra/ai-town#99]
Followed readme, but I'm getting an error when the dev instance starts up and conversations don't seem to progress.

This is the error pop-up
---
Unhandled Runtime Error
Error: Not Found
Call Stack
s

https://xxxx.clerk.accounts.dev/npm/@clerk/clerk-js@4.53.0/dist/clerk.browser.js (2:134751)
<unknown>

https://xxxx.clerk.accounts.dev/npm/@clerk/clerk-js@4.53.0/dist/clerk.browser.js (2:77226)

**Comment by ericvh** [comment]
Okay, my fault, I put in issuer not JWKS endpoint....

**Comment by Michael-A-Costa** [comment]
Hey man can you share your solution, I can't tell what I'm doing wrong here.
I have my Convex set up like this 
`CLERK_ISSUER_URL = https://abc-def-123.clerk.accounts.dev/.well-known/jwks.json`
But I get this error
`POST https://abc-def-123.clerk.accounts.dev/v1/client/sessions/sess_***/tokens/convex?_clerk_js_version=4.53.0&__dev_session=**** 404` 
which leads to some exceptions
`clerk.browser.js:2 Uncaught (in promise) Error
    at o._fetch (clerk.browser.js:2:77218)
    at async H.create (clerk.browser.js:2:107563)`

**Comment by ericvh** [comment]
mine was solved by having the well-known in place -- don't think I saw the other problem.
